# Exploring Airports in Australia

In [1]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json

# Import API key
from config import geoapify_key

## DataFrame Preparation

In [2]:
# Import cities file as DataFrame

        City
0     Sydney
1  Melbourne
2      Perth
3     Cairns
4   Adelaide

In [3]:
# Add columns the airports data we will fetch using the Geoapify API
# Note that we used "" to specify initial entry.

        City Lat Lon Airport Name IATA Name Airport Address Distance Website
0     Sydney
1  Melbourne
2      Perth
3     Cairns
4   Adelaide

## Look for Geographical Coordinates for Each City

In [4]:
# Define the API parameters
params = {
    "apiKey":geoapify_key,
    "format":"json"
}

# Set the base URL
base_url = "https://api.geoapify.com/v1/geocode/search"

In [5]:
# Print a message to follow up the airport search
print("Starting airport search")

# Loop through the cities_pd DataFrame and search coordinates for each city
for index, row in cities_pd.iterrows():

    # Get the city's name & add ", Australia" to the string so geoapify finds the correct city
    

    # Add the current city to the parameters


    # Make the API request

    
    # Convert response to JSON


    # Extract latitude and longitude

    
    # Log the search results
    print(f"Coordinates for {city} fetched...")

# Display sample data to confirm that the coordinates appear

Starting airport search
Coordinates for Sydney, Australia fetched...
Coordinates for Melbourne, Australia fetched...
Coordinates for Perth, Australia fetched...
Coordinates for Cairns, Australia fetched...
Coordinates for Adelaide, Australia fetched...
Coordinates for Gold Coast, Australia fetched...
Coordinates for Townsville, Australia fetched...
Coordinates for Williamtown, Australia fetched...

,City,Lat,Lon,Airport Name,IATA Name,Airport Address,Distance,Website
0,Sydney,-33.869844,151.208285,,,,,
1,Melbourne,-37.814218,144.963161,,,,,
2,Perth,-31.955896,115.86058,,,,,
3,Cairns,-16.920666,145.772185,,,,,
4,Adelaide,-34.928181,138.599931,,,,,

## Retrieve Airports' Information

In [6]:
# Set parameters to search for airport's details
radius = 50000
params = {
    "categories":"airport",
    "apiKey": geoapify_key,
    "limit":20
}

# Print a message to follow up the airport search
print("Starting airport details search")

# Iterate through the types_df DataFrame
for index, row in cities_pd.iterrows():
    
    # Get the city's name

    
    # Get latitude, longitude from the DataFrame

    
    # Add the current city's latitude and longitude to the params dictionary
    params["filter"] = f"circle:{longitude},{latitude},{radius}"
    params["bias"] = f"proximity:{longitude},{latitude}"
    
    # Set base URL
    base_url = "https://api.geoapify.com/v2/places"
           
    # Make an API request using the params dictionary

        
    # Convert the API response to JSON format

    
    # Grab the first airport from the results and store the details in the DataFrame
    try:

    except KeyError as e:
        # If no airport is found, log the error.
        print(f"{e.args[0]} not found for {cities_pd.loc[index, 'Airport Name']}")
        
    # Log the search results
    print(f"nearest airport from {city}: {cities_pd.loc[index, 'Airport Name']}")

# Display sample data

Starting airport details search
nearest airport from Sydney: Sydney (Kingsford Smith) Airport
nearest airport from Melbourne: Essendon Fields Airport
nearest airport from Perth: Perth Airport
website not found for Cairns Airport
nearest airport from Cairns: Cairns Airport
nearest airport from Adelaide: Adelaide Airport
nearest airport from Gold Coast: Gold Coast Airport
nearest airport from Townsville: Townsville Airport
nearest airport from Williamtown: Newcastle Airport

,City,Lat,Lon,Airport Name,IATA Name,Airport Address,Distance,Website
0,Sydney,-33.869844,151.208285,Sydney (Kingsford Smith) Airport,SYD,"McFall Street, Botany NSW 2019, Australia",6742,https://www.sydneyairport.com.au/
1,Melbourne,-37.814218,144.963161,Essendon Fields Airport,MEB,"72 Hargrave Avenue, Essendon Fields VIC 3041, ...",9980,https://www.ef.com.au/
2,Perth,-31.955896,115.86058,Perth Airport,PER,"Perth Airport WA 6104, Australia",8775,https://www.perthairport.com.au/
3,Cairns,-16.920666,145.772185,Cairns Airport,CNS,"Caudron Avenue, Aeroglen QLD 4870, Australia",3461,
4,Adelaide,-34.928181,138.599931,Adelaide Airport,ADL,"Adelaide Airport SA 5950, Australia",4898,https://www.adelaideairport.com.au/
5,Gold Coast,-28.002373,153.414599,Gold Coast Airport,OOL,"Golden Four Drive, Gold Coast City QLD 4225, A...",18807,https://www.goldcoastairport.com.au/
6,Townsville,-19.256939,146.823954,Townsville Airport,TSV,"Sunderland Street, Garbutt QLD 4810, Australia",4711,https://www.townsvilleairport.com.au/
7,Williamtown,-32.815,151.842778,Newcastle Airport,NTL,"55 Slades Road, Williamtown NSW 2318, Australia",620,https://www.newcastleairport.com.au

In [7]:
# Save Data to CSV